# Generated by Django 3.1.3 on 2020-11-30 19:27

# Django
import django.utils.timezone
from django.db import migrations, models

# Third Party Libraries
import model_utils.fields

# Kando
import kando.attachments.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=kando.attachments.models.file_upload_path
                    ),
                ),
                ("media_type", models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={"abstract": False,},
        ),
    ]
