# Generated by Django 3.1.3 on 2020-11-30 19:27

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cards", "0001_initial"),
        ("attachments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="card",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cards.card",
            ),
        ),
    ]
