# Generated by Django 3.1.3 on 2020-11-27 21:07

# Django
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cards", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="card", name="assignees",),
        migrations.AddField(
            model_name="card",
            name="assignee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_cards",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
