# Generated by Django 3.1.3 on 2020-11-29 22:17

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("swimlanes", "0001_initial"),
        ("cards", "0002_auto_20201127_2107"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="swimlane",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="swimlanes.swimlane",
            ),
        ),
    ]
