# Generated by Django 3.1.3 on 2020-11-28 14:26

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_auto_20201127_2307"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="projectmember",
            constraint=models.UniqueConstraint(
                fields=("project", "user"), name="unique_project_member"
            ),
        ),
    ]
