# Generated by Django 3.1.3 on 2020-11-29 17:57

# Django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_auto_20201128_1426"),
    ]

    operations = [
        migrations.RemoveField(model_name="project", name="is_private",),
    ]
