# Generated by Django 3.1.3 on 2020-11-29 18:04

# Django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_remove_project_is_private"),
    ]

    operations = [
        migrations.RemoveField(model_name="project", name="task_limit",),
    ]
