# Generated by Django 3.1.3 on 2020-11-29 11:28

# Django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invites", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(model_name="invite", name="unique_project_invite",),
    ]
