# Generated by Django 3.1.3 on 2020-11-27 13:25

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("swimlanes", "0001_initial"),
        ("columns", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="column",
            name="swimlane",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="swimlanes.swimlane",
            ),
        ),
    ]
