# Generated by Django 3.1.3 on 2020-11-29 22:17

# Django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("columns", "0002_column_swimlane"),
    ]

    operations = [
        migrations.RemoveField(model_name="column", name="swimlane",),
    ]
