# Generated by Django 3.1.3 on 2020-11-30 00:20

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("columns", "0003_remove_column_swimlane"),
    ]

    operations = [
        migrations.AlterField(
            model_name="column", name="name", field=models.CharField(max_length=60),
        ),
    ]
